name: Release Windows

on:
  release:
    types: [published]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Native Windows Host
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Create Zip Archive
        run: |
          Compress-Archive -Path '.\resources\*' -DestinationPath '.\release-windows-x86-64.zip'
          dir
          cd build
          Compress-Archive -Update -Path '.\raylib-gamepadtest.exe' -DestinationPath '..\release-windows-x86-64.zip'
      - run: gh release upload ${{github.event.release.tag_name}} release-windows-x86-64.zip
        env:
          GH_TOKEN: ${{ github.token }}