name: Release macOS

on:
  release:
    types: [published]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build arm64
        run: |
          cmake -B build_arm64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0
          cmake --build build_arm64
      - name: Build x86_64
        run: |
          cmake -B build_x86_64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0
          cmake --build build_x86_64
      - name: Create universal binary
        run: |
          lipo -create build_x86_64/raylib-gamepadtest build_arm64/raylib-gamepadtest -output raylib-gamepadtest
          zip -x .DS_Store release-mac.zip -r resources raylib-gamepadtest
      - name: Upload asset to release
        run: gh release upload ${{ github.event.release.tag_name }} release-mac.zip
        env:
          GH_TOKEN: ${{ github.token }}