name: Release Linux

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Native Linux Host
        run: |
          sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libwayland-bin libxkbcommon-dev
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          zip -r release-linux-x86-64.zip resources
          cd build
          zip ../release-linux-x86-64.zip raylib-gamepadtest
      - run: gh release upload ${{github.event.release.tag_name}} release-linux-x86-64.zip
        env:
          GH_TOKEN: ${{ github.token }}